# Generated by Django 2.0.6 on 2018-07-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20180711_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='work_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
