# Generated by Django 2.1.3 on 2018-12-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
